# Generated by Django 4.2.8 on 2023-12-17 17:52

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    replaces = [('slider', '0001_initial'), ('slider', '0002_picture_visible'), ('slider', '0003_alter_picture_picture'), ('slider', '0004_rename_picture_picture_file'), ('slider', '0005_picture_author')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.ImageField(max_length=255, upload_to='')),
                ('visible', models.BooleanField(default=True)),
                ('author', models.CharField(default='.', max_length=255)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
