# Generated by Django 4.2.8 on 2023-12-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_squashed_0005_picture_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
