# Generated by Django 5.0.2 on 2024-03-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0006_alter_picture_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_visibility', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
