# Generated by Django 5.0.2 on 2024-05-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0008_settings_uploads_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='offline',
            field=models.BooleanField(default=False),
        ),
    ]
